### ISSUE TITLE
关于图像与文本特征问题

### ISSUE THREAD

**Issue by ririv** [OreOZhao/MoSE4MKGC#1]
您好，你给出的代码中并没有关于提取图像与文本特征的代码，而是需要手动提取，所以请问，这两个pickle的内容形式是怎样的，我看到里面应该存储的是numpy格式文件，如果设这样，比如特征的排序顺序，大小等等又是怎样的呢，或者可否把这部分代码给出，我们自己跑一下

**Comment by OreOZhao** [comment]
您好，感谢对我们工作的关注。
图像和文本的pickle文件存储了形状为E*dim的numpy.array矩阵，E为数据集实体总数，dim为文本/图像特征的维度大小，顺序和process_datasets.py中输出的ent_id文件中实体顺序相同。

**Comment by KiteYN** [comment]
> 

您好，请问您在通过[mmkb](https://github.com/mniepert/mmkb)提供的URL链接下载 FB15K 的图片时，是否存在有实体没有图片的情况？如果存在，请问您是怎么处理的呢？

**Comment by KiteYN** [comment]
你好！已收到你的邮件！谢谢！

**Comment by Maigewm** [comment]
> 您好，你给出的代码中并没有关于提取图像与文本特征的代码，而是需要手动提取，所以请问，这两个pickle的内容形式是怎样的，我看到里面应该存储的是numpy格式文件，如果设这样，比如特征的排序顺序，大小等等又是怎样的呢，或者可否把这部分代码给出，我们自己跑一下

你好，请问您现在是否已经跑通了呢？训练大概需要多长时间呢？

**Comment by KiteYN** [comment]
你好！已收到你的邮件！谢谢！
