### ISSUE TITLE
Please provide multimodal pre-training files

### ISSUE THREAD

**Issue by CuteMing** [OreOZhao/MoSE4MKGC#2]
Thanks for sharing. Could you please upload the pre-trained files? Such as text_feature.pickle, img_feature.pickle.

**Comment by OreOZhao** [comment]
Thank you for your attention!

We update the image and text encoder code in `src/img_encoder.py` and `src/text_encoder.py` which output the pickle files needed.

Hope it solves your problem. If you have any further problems, feel free to contact me.
