### ISSUE TITLE
How long will it take for the whole processing and traning procedure?

### ISSUE THREAD

**Issue by Maigewm** [OreOZhao/MoSE4MKGC#3]
And I wonder how much memory will this model use most?
Hope for your reply. This is very important for me!

**Comment by OreOZhao** [comment]
Thank you for your attention and sorry for the late reply.

The computation time cost and memory usage of training are shown below. We only list a group of experiments as an example and the average cost of MoSE should be similar. We run our experiments on a single NVIDIA A6000 GPU with 48GB of RAM.

|   |  FB15K-237   | WN18  | WN9 |
| ----  |  ----  | ----  | ----  |
| average seconds per epoch  | 52 | 66 | 3 |
| epoch  | 53 | 56 | 26 |
| memory usage (MiB) | 5671 | 10273 | 3865 |
