### ISSUE TITLE
Could not reproduce the results without the **.pickle file

### ISSUE THREAD

**Issue by Williamqiang** [OreOZhao/MoSE4MKGC#4]
Please supply the feature pickle file, we couldn‘t verify the effectiveness of your approach!!!

**Comment by OreOZhao** [comment]
Thank you for your attention!

We update the image and text encoder code in `src/img_encoder.py` and `src/text_encoder.py` which output the pickle files needed. 

Hope it solves your problem. If you have any further problems about reproduction of the results, feel free to contact me.

**Comment by gela-Su** [comment]
For the FB15k-237 dataset, there are multiple images per entity, how to deal with it when extracting features? 
Looking forward to your answer. Thank you!
