### ISSUE TITLE
Entity images download

### ISSUE THREAD

**Issue by wxxw-blip** [OreOZhao/MoSE4MKGC#5]
您好，请问您能否提供WN18和WN9的图片文件，可以上传到[GoogleDrive]吗？

**Comment by OreOZhao** [comment]
Kindly reminder that you could find the Google Drive link or Baidu Netdisk link in [MKGformer](https://github.com/zjunlp/MKGformer) : ) 

You could also crawl the image set yourself with the help of [MMKB](https://github.com/mniepert/mmkb) or [RSME](https://github.com/wangmengsd/RSME).

**Comment by wxxw-blip** [comment]
您好，感谢回复，我试过了以上方法，只能爬取到7,801个实体有图片文件，实在有限，请问您可以提供一下数据集吗？十分感谢！

**Comment by OreOZhao** [comment]
和您类似，我们同样面临实体图像缺失问题。在这个工作中，我们采用了随机变量（np.random.normal）代替没有图像的实体特征（src/img_encoder.py）。如果您有更好的解决方法，欢迎与我分享。

**Comment by wxxw-blip** [comment]
好的，谢谢您的回复
